### PR TITLE
Created motivation model, type, and mutations.

### PR DESCRIPTION
**Pull request by schen196**
Also added try and catch for all queries and mutations in case of possible error (ex: MongoDB not connected properly)

### CODE REVIEW

**Comment by schen196** [comment]
Made a typo

**Comment by schen196** [comment]
Added query to get a random motivation tip. Added mongoose-simple-random dependency.

**Comment by schen196** [comment]
Made some advancements and added more mutations to schema. Added the backend functions for calling the get, post, and put.

**Review by Deaniesaur — CHANGES_REQUESTED** [review]
GraphQL handles Errors by default. We would only want to catch errors if want to return specific messages. Also, if you catch errors like this, the response will return an OK/200 status even though an error occurred.

In our case, I believe that the default handling of GraphQL is sufficient in our use case so its just better to remove the Try/Catch

**Comment by schen196** [comment]
I have applied the requested changes :)

**Pull request merged**
